# Generated by Django 5.2.3 on 2025-06-15 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cart', '0002_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='enginereview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='engine',
            name='displacement_liters',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Объем (литры)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='power_hp',
            field=models.PositiveIntegerField(default=1, verbose_name='Мощность (л.с.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='torque_nm',
            field=models.PositiveIntegerField(default=10, verbose_name='Крутящий момент (Нм)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='auth.group', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EngineSpecification',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
