# Generated by Django 5.2.3 on 2025-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0002_news_remove_user_role_alter_enginereview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='engines/', verbose_name='Фото двигателя'),
        ),
    ]
